[app]
name = "Hilbert"
category = "Badge"

[entry]
class = "Hilbert"

[metadata]
author = "pikesley"
license = "MIT"
url = "https://www.github.com/pikesley/tildagon-hilbert"
description = "Fractal curves on your badge. CONFIRM button to step to the next curve"
version = "0.0.2"
